# Generated by Django 5.0.4 on 2024-05-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of publication'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.publisher', verbose_name='publisher'),
        ),
    ]
